<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions xmlns:wsap="http://schemas.xmlsoap.org/ws/2004/08/addressing/policy" xmlns:wsa10="http://www.w3.org/2005/08/addressing" xmlns:tns="http://schemas.navitaire.com/WebServices" xmlns:msc="http://schemas.microsoft.com/ws/2005/12/wsdl/contract" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:wsx="http://schemas.xmlsoap.org/ws/2004/09/mex" xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata" xmlns:wsa="http://schemas.xmlsoap.org/ws/2004/08/addressing" xmlns:wsaw="http://www.w3.org/2006/05/addressing/wsdl" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="UtilitiesManager" targetNamespace="http://schemas.navitaire.com/WebServices" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <wsp:Policy wsu:Id="BasicHttpBinding_IUtilitiesManager_policy">
    <wsp:ExactlyOne>
      <wsp:All>
        <sp:TransportBinding xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <wsp:Policy>
            <sp:TransportToken>
              <wsp:Policy>
                <sp:HttpsToken RequireClientCertificate="false" />
              </wsp:Policy>
            </sp:TransportToken>
            <sp:AlgorithmSuite>
              <wsp:Policy>
                <sp:Basic256 />
              </wsp:Policy>
            </sp:AlgorithmSuite>
            <sp:Layout>
              <wsp:Policy>
                <sp:Strict />
              </wsp:Policy>
            </sp:Layout>
          </wsp:Policy>
        </sp:TransportBinding>
      </wsp:All>
    </wsp:ExactlyOne>
  </wsp:Policy>
  <wsdl:types>
    <xsd:schema targetNamespace="http://schemas.navitaire.com/WebServices/Imports">
      <xsd:import schemaLocation="https://aktestr3xapi.navitaire.com/UtilitiesManager.svc?xsd=xsd0" namespace="http://schemas.navitaire.com/WebServices/ServiceContracts/UtilitiesService" />
      <xsd:import schemaLocation="https://aktestr3xapi.navitaire.com/UtilitiesManager.svc?xsd=xsd2" namespace="http://schemas.navitaire.com/WebServices" />
      <xsd:import schemaLocation="https://aktestr3xapi.navitaire.com/UtilitiesManager.svc?xsd=xsd1" namespace="http://schemas.microsoft.com/2003/10/Serialization/" />
      <xsd:import schemaLocation="https://aktestr3xapi.navitaire.com/UtilitiesManager.svc?xsd=xsd3" namespace="http://schemas.navitaire.com/WebServices/DataContracts/Utilities" />
      <xsd:import schemaLocation="https://aktestr3xapi.navitaire.com/UtilitiesManager.svc?xsd=xsd4" namespace="http://schemas.navitaire.com/WebServices/DataContracts/Common/Enumerations" />
    </xsd:schema>
  </wsdl:types>
  <wsdl:message name="GetExternalRateListRequest">
    <wsdl:part xmlns:q1="http://schemas.navitaire.com/WebServices/ServiceContracts/UtilitiesService" name="parameters" element="q1:GetExternalRateListRequest" />
  </wsdl:message>
  <wsdl:message name="GetExternalRateListRequest_Headers">
    <wsdl:part name="ContractVersion" element="tns:ContractVersion" />
    <wsdl:part name="Signature" element="tns:Signature" />
  </wsdl:message>
  <wsdl:message name="GetExternalRateListResponse">
    <wsdl:part xmlns:q2="http://schemas.navitaire.com/WebServices/ServiceContracts/UtilitiesService" name="parameters" element="q2:GetExternalRateListResponse" />
  </wsdl:message>
  <wsdl:portType name="IUtilitiesManager">
    <wsdl:operation name="GetExternalRateList">
      <wsdl:input wsaw:Action="http://schemas.navitaire.com/WebServices/IUtilitiesManager/GetExternalRateList" name="GetExternalRateListRequest" message="tns:GetExternalRateListRequest" />
      <wsdl:output wsaw:Action="http://schemas.navitaire.com/WebServices/IUtilitiesManager/GetExternalRateListResponse" name="GetExternalRateListResponse" message="tns:GetExternalRateListResponse" />
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="BasicHttpBinding_IUtilitiesManager" type="tns:IUtilitiesManager">
    <wsp:PolicyReference URI="#BasicHttpBinding_IUtilitiesManager_policy" />
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http" />
    <wsdl:operation name="GetExternalRateList">
      <soap:operation soapAction="http://schemas.navitaire.com/WebServices/IUtilitiesManager/GetExternalRateList" style="document" />
      <wsdl:input name="GetExternalRateListRequest">
        <soap:header message="tns:GetExternalRateListRequest_Headers" part="ContractVersion" use="literal" />
        <soap:header message="tns:GetExternalRateListRequest_Headers" part="Signature" use="literal" />
        <soap:body use="literal" />
      </wsdl:input>
      <wsdl:output name="GetExternalRateListResponse">
        <soap:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="UtilitiesManager">
    <wsdl:port name="BasicHttpBinding_IUtilitiesManager" binding="tns:BasicHttpBinding_IUtilitiesManager">
      <soap:address location="https://aktestr3xapi.navitaire.com/UtilitiesManager.svc" />
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>